
spring.application.name=RuneScape-AI
spring.datasource.url=jdbc:postgresql://localhost:5432/runescape_ai
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=luap.
spring.datasource.password=